/* Generated by bun scripts/generate-review-types.ts from the agent_review OpenAPI contract. */

/**
 * Reanchoring outcome; an ambiguous match never silently moves a comment.
 */
export type AnchorStatus = 'current' | 'moved' | 'outdated';
/**
 * Message author, assigned by authentication rather than client JSON.
 */
export type Author =
  | {
      /**
       * Authenticated Macro user identifier.
       */
      id: string;
      kind: 'user';
    }
  | {
      kind: 'agent';
    };
/**
 * Feedback delivery state backed by a durable outbox.
 */
export type Delivery = 'pending' | 'queued' | 'failed';
export type FileStatus =
  | 'added'
  | 'deleted'
  | 'modified'
  | 'renamed'
  | 'unchanged';
/**
 * An aligned pair of 0-based line indices; `None` where one side has no line.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Row = [number | null, number | null];
/**
 * Optional agent preference for the diagram's reading direction.
 */
export type GraphDirection = 'leftToRight' | 'topToBottom';
/**
 * Why a file's contents aren't shown.
 */
export type Omitted = 'binary' | 'tooLarge' | 'submodule';
export type Side = 'old' | 'new';
/**
 * A stable identity shared by revision links, annotations, and conversations.
 */
export type ReviewId = string;
/**
 * Source availability shown honestly by the reader.
 */
export type SourceKind = 'workspace' | 'pullRequest';

export interface ReviewWireTypes {
  Anchor?: Anchor;
  AnchorStatus?: AnchorStatus;
  Annotation?: Annotation;
  Author?: Author;
  Chapter?: Chapter;
  Comment?: Comment;
  Comparison?: Comparison;
  Delivery?: Delivery;
  FileDiff?: FileDiff;
  FileEntry?: FileEntry;
  FileGroup?: FileGroup;
  FileStatus?: FileStatus;
  GraphDirection?: GraphDirection;
  GraphEdge?: GraphEdge;
  GraphNode?: GraphNode;
  LinkBody?: LinkBody;
  Location?: Location7;
  Message?: Message;
  Omitted?: Omitted;
  ResolveBody?: ResolveBody;
  ResolveResponse?: ResolveResponse;
  Review?: Review;
  ReviewGraph?: ReviewGraph2;
  ReviewId?: ReviewId;
  ReviewLink?: ReviewLink;
  ReviewResponse?: ReviewResponse;
  Revision?: Revision;
  Row?: Row;
  Side?: Side;
  SideText?: SideText;
  SourceKind?: SourceKind;
  Symbol?: Symbol;
  Thread?: Thread;
}
/**
 * A durable code link with preserved original context.
 */
export interface Anchor {
  /**
   * Stable identity used in URLs.
   */
  id: string;
  /**
   * Revision the author was viewing.
   */
  revision: number;
  original: Location;
  /**
   * Exact selected lines, never replaced by a later capture.
   */
  excerpt: string[];
  current: Location1;
  /**
   * How the current selection relates to the original.
   */
  status: 'current' | 'moved' | 'outdated';
}
/**
 * Original selection.
 */
export interface Location {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * Latest resolved selection.
 */
export interface Location1 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * An explanation pinned next to code.
 */
export interface Annotation {
  /**
   * Stable key, reused to update the explanation.
   */
  key: string;
  location: Location2;
  /**
   * Markdown explanation.
   */
  body: string;
}
/**
 * Where this explanation belongs.
 */
export interface Location2 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * A chapter authored by the agent. Keys allow idempotent replacement.
 */
export interface Chapter {
  /**
   * Stable agent-supplied key.
   */
  key: string;
  /**
   * Short title describing intent.
   */
  title: string;
  /**
   * Markdown explanation of why these changes belong together.
   */
  description: string;
  /**
   * Reading order of repository-relative files.
   */
  paths: string[];
  focus: Location3;
}
/**
 * Initial code selection, validated against the published revision.
 */
export interface Location3 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * A user comment or reply request.
 */
export interface Comment {
  /**
   * UUID reused for retries.
   */
  id: string;
  /**
   * Existing thread for a reply; absent creates a new thread.
   */
  thread?: string | null;
  /**
   * Revision the user saw.
   */
  revision: number;
  location?: Location4 | null;
  /**
   * Markdown comment text.
   */
  body: string;
}
/**
 * Required for a new thread.
 */
export interface Location4 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * What content the runtime should compare. The base is pinned after capture.
 */
export interface Comparison {
  /**
   * Base commit or branch; defaults to HEAD for a new workspace review.
   */
  base?: string | null;
  /**
   * Explicitly switch a fixed-head workspace comparison back to the live worktree.
   */
  worktree?: boolean;
  /**
   * Optional tip commit; absent keeps the previous workspace tip or follows the PR.
   */
  head?: string | null;
}
/**
 * One file's diff: both sides in full, aligned line by line.
 */
export interface FileDiff {
  path: string;
  oldPath?: string | null;
  status: FileStatus;
  /**
   * Display name of the language, when we recognise it.
   */
  language?: string | null;
  omitted?: ('binary' | 'tooLarge' | 'submodule') | null;
  /**
   * Changes the rows can't show: the file mode, line endings, the final
   * newline, a submodule's commit. Short phrases, e.g. "mode 100644 → 100755".
   */
  details?: string[];
  /**
   * Why the file starts collapsed (set by the agent, e.g. "generated by ts-rs").
   */
  collapsed?: string | null;
  /**
   * What kind of file it is, as diffd can tell by itself: `test`, `generated`.
   */
  labels?: string[];
  added: number;
  removed: number;
  old?: SideText | null;
  new?: SideText | null;
  /**
   * The whole file, aligned: (old line index, new line index), 0-based.
   */
  rows: Row[];
  /**
   * New-side lines (1-based) that changed since the previous revision.
   */
  since: number[];
}
/**
 * One side of a file.
 */
export interface SideText {
  lines: string[];
  /**
   * Per line, flattened `[start, end, class, start, end, class, …]`.
   * `class` indexes [`SyntaxClass::ALL`].
   */
  syntax: number[][];
  /**
   * Per line, flattened `[start, end, …]`: tokens difftastic marks as novel.
   */
  novel: number[][];
}
/**
 * One file in the manifest, fetched independently by content identity.
 */
export interface FileEntry {
  /**
   * Repository-relative path, including deletions.
   */
  path: string;
  /**
   * Original path of a rename.
   */
  oldPath?: string | null;
  /**
   * Session-scoped immutable body identifier.
   */
  content: string;
  /**
   * Engine file status.
   */
  status: 'added' | 'deleted' | 'modified' | 'renamed' | 'unchanged';
  /**
   * Language when recognized.
   */
  language?: string | null;
  /**
   * Changed lines on the new side.
   */
  added: number;
  /**
   * Changed lines on the old side.
   */
  removed: number;
  /**
   * Explanation for a collapsed generated file.
   */
  collapsed?: string | null;
  /**
   * Semantic labels from diffd or the agent.
   */
  labels: string[];
  omitted?: ('binary' | 'tooLarge' | 'submodule') | null;
}
/**
 * A named set of files the reviewer can hide and reveal together.
 */
export interface FileGroup {
  /**
   * Stable agent-supplied key.
   */
  key: string;
  /**
   * Short label, such as Generated or Tests.
   */
  title: string;
  /**
   * Paths, directories, or globs when publishing (e.g. .sqlx/**, ** /*.test.ts).
   * Reads expand these to exact paths in the requested revision.
   */
  files: string[];
  /**
   * Whether these files start hidden. The reader can always reveal them.
   */
  hidden?: boolean;
}
/**
 * A relationship, optionally linked to the call site that implements it.
 */
export interface GraphEdge {
  /**
   * Source component ID.
   */
  from: string;
  /**
   * Destination component ID.
   */
  to: string;
  /**
   * Short verb describing the relationship.
   */
  label: string;
  location?: Location5 | null;
}
/**
 * Optional call site to reveal when clicked.
 */
export interface Location5 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * A component linked to its implementation in this revision.
 */
export interface GraphNode {
  /**
   * Unique component identity within the map.
   */
  id: string;
  /**
   * Short component name.
   */
  title: string;
  /**
   * Optional concise explanation of this component's role or change (180 characters).
   */
  description?: string | null;
  /**
   * Optional agent-chosen category, such as UI, Runtime, or Storage (32 characters).
   */
  kind?: string | null;
  /**
   * Optional containing component ID. Zooming reveals children inside their
   * parent. Use up to four levels, from broad components to specific code areas.
   * Parent references must exist and cannot form cycles.
   */
  parent?: string | null;
  /**
   * Changed paths, directories, or globs belonging to this component.
   * Omitted or empty uses the linked file. Reads expand patterns to exact paths;
   * the reader derives actual change counts rather than trusting authored totals.
   */
  files?: string[];
  location: Location6;
}
/**
 * Implementation to reveal when clicked.
 */
export interface Location6 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
export interface LinkBody {
  revision: number;
  location: Location7;
}
/**
 * A code reference supplied by a user or agent; lines are one-based, inclusive.
 */
export interface Location7 {
  /**
   * Repository-relative path.
   */
  path: string;
  /**
   * Before or after side.
   */
  side: 'old' | 'new';
  /**
   * First selected line.
   */
  line: number;
  /**
   * Last selected line; omitted for a single line.
   */
  endLine?: number | null;
}
/**
 * An immutable thread message. Its ID is also its retry key.
 */
export interface Message {
  /**
   * Caller-minted UUID reused for network retries.
   */
  id: string;
  /**
   * Message author, assigned by authentication rather than client JSON.
   */
  author:
    | {
        /**
         * Authenticated Macro user identifier.
         */
        id: string;
        kind: 'user';
      }
    | {
        kind: 'agent';
      };
  /**
   * Markdown body.
   */
  body: string;
  /**
   * Time accepted by the review store.
   */
  createdAt: string;
  delivery?: ('pending' | 'queued' | 'failed') | null;
}
export interface ResolveBody {
  thread: string;
  resolved: boolean;
}
/**
 * Result of changing a thread's resolution state.
 */
export interface ResolveResponse {
  /**
   * The saved state.
   */
  resolved: boolean;
}
/**
 * Durable aggregate protected by a compare-and-swap version.
 */
export interface Review {
  /**
   * Stable review ID.
   */
  id: string;
  /**
   * Owning session; never supplied by an MCP tool argument.
   */
  sessionId: string;
  /**
   * Metadata/activity version, independent of code revisions.
   */
  version: number;
  /**
   * Display title.
   */
  title: string;
  /**
   * Agent summary.
   */
  summary: string;
  /**
   * Repository name or URL.
   */
  repository: string;
  /**
   * Availability of uncommitted changes.
   */
  source: 'workspace' | 'pullRequest';
  /**
   * Immutable revision history.
   */
  revisions: Revision[];
  /**
   * Current reading tour.
   */
  tour: Chapter[];
  /**
   * Current inline explanations.
   */
  annotations: Annotation[];
  /**
   * Current agent-selected file groups.
   */
  fileGroups?: FileGroup[];
  graph?: ReviewGraph1 | null;
  /**
   * Durable selections.
   */
  anchors: Anchor[];
  /**
   * Durable discussion.
   */
  threads: Thread[];
}
/**
 * One immutable revision; older links keep resolving after new captures.
 */
export interface Revision {
  /**
   * Monotonic, one-based revision number.
   */
  number: number;
  /**
   * Time this revision was published.
   */
  createdAt: string;
  comparison: Comparison1;
  /**
   * Lazy body references.
   */
  files: FileEntry[];
  /**
   * Tour as it was explained for this revision.
   */
  tour?: Chapter[];
  /**
   * Inline explanations belonging to this revision.
   */
  annotations?: Annotation[];
  /**
   * Agent-selected file groups for this revision.
   */
  fileGroups?: FileGroup[];
  graph?: ReviewGraph | null;
  /**
   * Definitions indexed by diffd across the snapshot.
   */
  symbols: Symbol[];
}
/**
 * What content the runtime should compare. The base is pinned after capture.
 */
export interface Comparison1 {
  /**
   * Base commit or branch; defaults to HEAD for a new workspace review.
   */
  base?: string | null;
  /**
   * Explicitly switch a fixed-head workspace comparison back to the live worktree.
   */
  worktree?: boolean;
  /**
   * Optional tip commit; absent keeps the previous workspace tip or follows the PR.
   */
  head?: string | null;
}
/**
 * Agent-authored component map for this revision.
 */
export interface ReviewGraph {
  /**
   * Short description of what the map explains.
   */
  title: string;
  direction?: ('leftToRight' | 'topToBottom') | null;
  /**
   * Components in reading order (up to 64). An empty list clears the map.
   */
  nodes: GraphNode[];
  /**
   * Directed relationships between components.
   */
  edges: GraphEdge[];
}
/**
 * A definition found by the tags queries: what `gd` jumps to.
 */
export interface Symbol {
  name: string;
  /**
   * e.g. "function", "class", "method", "module".
   */
  kind: string;
  /**
   * Index into [`Snapshot::files`].
   */
  file: number;
  side: Side;
  line: number;
  start: number;
  end: number;
  /**
   * The whole definition's first and last line (1-based), e.g. a function with its body.
   *
   * @minItems 2
   * @maxItems 2
   */
  lines: [number, number];
}
/**
 * Current component map.
 */
export interface ReviewGraph1 {
  /**
   * Short description of what the map explains.
   */
  title: string;
  direction?: ('leftToRight' | 'topToBottom') | null;
  /**
   * Components in reading order (up to 64). An empty list clears the map.
   */
  nodes: GraphNode[];
  /**
   * Directed relationships between components.
   */
  edges: GraphEdge[];
}
/**
 * A discussion whose identity survives revisions.
 */
export interface Thread {
  /**
   * Stable thread identity.
   */
  id: string;
  /**
   * Anchor in `Review.anchors`.
   */
  anchor: string;
  /**
   * Human-controlled resolution.
   */
  resolved: boolean;
  /**
   * Ordered, idempotent messages.
   */
  messages: Message[];
}
/**
 * A compact component or data-flow diagram authored by the agent.
 */
export interface ReviewGraph2 {
  /**
   * Short description of what the map explains.
   */
  title: string;
  direction?: ('leftToRight' | 'topToBottom') | null;
  /**
   * Components in reading order (up to 64). An empty list clears the map.
   */
  nodes: GraphNode[];
  /**
   * Directed relationships between components.
   */
  edges: GraphEdge[];
}
/**
 * A validated link returned to the agent.
 */
export interface ReviewLink {
  /**
   * A stable identity shared by revision links, annotations, and conversations.
   */
  reviewId: string;
  /**
   * Code revision, pinned in the URL.
   */
  revision: number;
  /**
   * Canonical Macro URL.
   */
  url: string;
}
/**
 * Review metadata envelope. An empty review is distinct from a failed read.
 */
export interface ReviewResponse {
  review?: Review1 | null;
}
/**
 * Durable aggregate protected by a compare-and-swap version.
 */
export interface Review1 {
  /**
   * Stable review ID.
   */
  id: string;
  /**
   * Owning session; never supplied by an MCP tool argument.
   */
  sessionId: string;
  /**
   * Metadata/activity version, independent of code revisions.
   */
  version: number;
  /**
   * Display title.
   */
  title: string;
  /**
   * Agent summary.
   */
  summary: string;
  /**
   * Repository name or URL.
   */
  repository: string;
  /**
   * Availability of uncommitted changes.
   */
  source: 'workspace' | 'pullRequest';
  /**
   * Immutable revision history.
   */
  revisions: Revision[];
  /**
   * Current reading tour.
   */
  tour: Chapter[];
  /**
   * Current inline explanations.
   */
  annotations: Annotation[];
  /**
   * Current agent-selected file groups.
   */
  fileGroups?: FileGroup[];
  graph?: ReviewGraph1 | null;
  /**
   * Durable selections.
   */
  anchors: Anchor[];
  /**
   * Durable discussion.
   */
  threads: Thread[];
}
