/** Generate review wire types from the Rust OpenAPI contract, including diffd-core. */
import { compile } from 'json-schema-to-typescript';

const source = process.argv[2];
if (!source) throw new Error('Usage: bun scripts/generate-review-types.ts <agent_review OpenAPI JSON>');
const raw = await Bun.file(source).json();
const schemas = JSON.parse(JSON.stringify(raw.components.schemas).replaceAll('#/components/schemas/', '#/$defs/'));
const schema = { type: 'object', properties: Object.fromEntries(Object.keys(schemas).map((name) => [name, { $ref: `#/$defs/${name}` }])), additionalProperties: false, $defs: schemas };
const types = await compile(schema, 'ReviewWireTypes', { bannerComment: '/* Generated by bun scripts/generate-review-types.ts from the agent_review OpenAPI contract. */', additionalProperties: false, unknownAny: false });
await Bun.write(new URL('../src/lib/service-clients/service-agent-harness/review-types.ts', import.meta.url), types);
